### ISSUE TITLE
[idea] Add background for center, section etc

### ISSUE THREAD

**Issue by Guray00** [estruyf/slidev-theme-the-unnamed#3]
Could be useful adding a background field in `center` and `section` to add more customization.

**Comment by estruyf** [comment]
I like the idea! Thanks @Guray00, for the suggestion! ❤️

**Comment by Guray00** [comment]
Thanks for your awesome work! I'm new in slidev themes, maybe I will be able to help in future!

**Comment by estruyf** [comment]
Cool! Just pushed out an update with this change. You are now able to set the background of the slide from the global configuration, or per slide.

**Comment by Guray00** [comment]
Thanks, working!
