### ISSUE TITLE
Titles not styled in two-columns layout

### ISSUE THREAD

**Issue by glepretre** [estruyf/slidev-theme-the-unnamed#4]
I needed a [two-columns layout](https://sli.dev/builtin/layouts.html#two-cols) recently and noticed the titles have no background in this case : 

```md
---
layout: two-cols
theme: the-unnamed
---

# Left

This shows on the left

::right::

# Right

This shows on the right

```

![image](https://github.com/estruyf/slidev-theme-the-unnamed/assets/5930831/ea866802-c59e-4ac8-8502-9d246df80f39)

**Comment by estruyf** [comment]
Pushed a new version. It's actually funny, I added the styles earlier this week. Thanks for the suggestion.

**Comment by glepretre** [comment]
Thank you :pray: :sunglasses:
