### ISSUE TITLE
Monaco not working with this theme

### ISSUE THREAD

**Issue by kristiankupsch** [estruyf/slidev-theme-the-unnamed#8]
When using a monaco block, monaco is not rendereing correctly:

Current Result:
![grafik](https://github.com/user-attachments/assets/41b46b02-453e-4a8f-8a63-be6cd6ec7b12)

Expected Result:
![grafik](https://github.com/user-attachments/assets/a287ec2f-f646-4b1e-adae-8313385ad31d)

**Comment by estruyf** [comment]
Hi @kristiankupsch, I've just added the support for the Monaco Editor in the theme. If you install version `0.0.22`, you should be able to use it.
